(function(root){'use strict';function calculate(input,mode='DEG',ans=0){
if(input.length>500)throw Error('นิพจน์ยาวเกินไป');if(!['DEG','RAD'].includes(mode))throw Error('หน่วยมุมไม่ถูกต้อง');
const s=input.replace(/×/g,'*').replace(/÷/g,'/').replace(/−/g,'-').replace(/π/g,'pi'),tokens=[];let i=0;
while(i<s.length){if(/\s/.test(s[i])){i++;continue;}const m=s.slice(i).match(/^(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][+-]?\d+)?|^[A-Za-z]+|^[+\-*/^()!%]/);if(!m)throw Error('มีอักขระที่ไม่รองรับ');tokens.push(m[0]);i+=m[0].length;}i=0;let depth=0;
const fail=()=>{throw Error('ตรวจเครื่องหมายและวงเล็บให้ครบ');};const finite=x=>{if(!Number.isFinite(x))throw Error('ผลลัพธ์ไม่อยู่ในขอบเขตจำนวนจริงหรือมีขนาดใหญ่เกินไป');return x;};
function expression(){let x=term();while(tokens[i]==='+'||tokens[i]==='-'){let op=tokens[i++],y=term();x=finite(op==='+'?x+y:x-y);}return x;}
function term(){let x=unary();while(tokens[i]==='*'||tokens[i]==='/'){let op=tokens[i++],y=unary();if(op==='/'&&y===0)throw Error('ไม่สามารถหารด้วยศูนย์');x=finite(op==='*'?x*y:x/y);}return x;}
function unary(){if(tokens[i]==='+'){i++;return unary();}if(tokens[i]==='-'){i++;return -unary();}return power();}
function power(){let x=postfix();if(tokens[i]==='^'){i++;let y=unary();if(x===0&&y===0)throw Error('ไม่กำหนดค่า 0^0');x=finite(Math.pow(x,y));}return x;}
function postfix(){let x=atom();while(tokens[i]==='!'||tokens[i]==='%'){const op=tokens[i++];if(op==='%')x/=100;else{if(!Number.isInteger(x)||x<0||x>170)throw Error('แฟกทอเรียลใช้จำนวนเต็ม 0 ถึง 170');let n=1;for(let j=2;j<=x;j++)n*=j;x=n;}}return x;}
function atom(){if(++depth>80)throw Error('นิพจน์ซับซ้อนเกินไป');let tok=tokens[i++],x;if(tok===undefined)fail();if(tok==='('){x=expression();if(tokens[i++]!==')')fail();}else if(/^\d|^\./.test(tok))x=finite(Number(tok));else if(tok==='pi')x=Math.PI;else if(tok==='e')x=Math.E;else if(tok==='Ans')x=ans;else{if(!['sin','cos','tan','asin','acos','atan','sqrt','ln','log','exp','abs'].includes(tok))throw Error('ไม่รู้จักฟังก์ชัน '+tok);if(tokens[i++]!=='(')fail();const v=expression();if(tokens[i++]!==')')fail();const rad=mode==='DEG'?v*Math.PI/180:v,convert=mode==='DEG'?180/Math.PI:1;if(tok==='tan'&&Math.abs(Math.cos(rad))<1e-14)throw Error('tan ไม่กำหนดที่มุมนี้');x=finite(({sin:()=>Math.sin(rad),cos:()=>Math.cos(rad),tan:()=>Math.tan(rad),asin:()=>Math.asin(v)*convert,acos:()=>Math.acos(v)*convert,atan:()=>Math.atan(v)*convert,sqrt:()=>Math.sqrt(v),ln:()=>Math.log(v),log:()=>Math.log10(v),exp:()=>Math.exp(v),abs:()=>Math.abs(v)})[tok]());}depth--;return x;}
const result=expression();if(i!==tokens.length)throw Error('ตรวจนิพจน์ และใส่เครื่องหมายคูณให้ครบ');return finite(result);}
if(typeof module!=='undefined')module.exports={calculate};else root.ScientificCalculator={calculate};})(typeof window!=='undefined'?window:{});
