'use strict';
const $=id=>document.getElementById(id), canvas=$('graph'),ctx=canvas.getContext('2d'),P=VectorPhysics;
const state={force:10,angle:30,components:true,values:true,running:false},cx=400,cy=340,scale=13;
const fmt=x=>(Math.abs(x)<.005?0:x).toFixed(2),rad=a=>a*Math.PI/180;
function arrow(x,y,X,Y,color,width=4){const len=Math.hypot(X-x,Y-y);if(len<.5)return;const a=Math.atan2(Y-y,X-x),head=Math.min(14,len*.45);ctx.strokeStyle=color;ctx.fillStyle=color;ctx.lineWidth=width;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(X,Y);ctx.stroke();ctx.beginPath();ctx.moveTo(X,Y);ctx.lineTo(X-head*Math.cos(a-.43),Y-head*Math.sin(a-.43));ctx.lineTo(X-head*Math.cos(a+.43),Y-head*Math.sin(a+.43));ctx.closePath();ctx.fill();}
function label(text,x,y,color='#18364e',align='left'){ctx.font='20px Sarabun, sans-serif';ctx.textAlign=align;ctx.fillStyle='rgba(251,253,255,.92)';const w=ctx.measureText(text).width;ctx.fillRect(align==='right'?x-w-5:align==='center'?x-w/2-5:x-5,y-22,w+10,29);ctx.fillStyle=color;ctx.fillText(text,x,y);}
function draw(){ctx.clearRect(0,0,800,680);ctx.lineWidth=1;ctx.strokeStyle='#e2ebf2';for(let x=cx-12*26;x<=cx+12*26;x+=26){ctx.beginPath();ctx.moveTo(x,28);ctx.lineTo(x,652);ctx.stroke();}for(let y=cy-12*26;y<=cy+12*26;y+=26){ctx.beginPath();ctx.moveTo(88,y);ctx.lineTo(712,y);ctx.stroke();}arrow(45,cy,755,cy,'#8198a8',2);arrow(cx,650,cx,25,'#8198a8',2);label('+x',752,cy-14,'#526d7c','right');label('+y',cx+12,33,'#526d7c');label('0',cx-16,cy+24,'#526d7c','right');
const c=P.components(state.force,state.angle),x=cx+c.x*scale,y=cy-c.y*scale;
if(state.force>0){ctx.beginPath();ctx.moveTo(cx,cy);ctx.arc(cx,cy,48,0,-rad(state.angle),true);ctx.closePath();ctx.fillStyle='#9978d61c';ctx.fill();ctx.beginPath();ctx.arc(cx,cy,48,0,-rad(state.angle),true);ctx.strokeStyle='#9270c3';ctx.lineWidth=2;ctx.stroke();}
if(state.components){ctx.setLineDash([7,6]);ctx.strokeStyle='#8da8bc';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x,cy);ctx.lineTo(x,y);ctx.lineTo(cx,y);ctx.stroke();ctx.setLineDash([]);arrow(cx,cy,x,cy,'#136dcc',5);arrow(cx,cy,cx,y,'#087b60',5);if(state.values){label('Fₓ = '+fmt(c.x)+' N',(cx+x)/2,cy+(c.y>=0?35:-20),'#136dcc','center');label('Fᵧ = '+fmt(c.y)+' N',cx+(c.x>=0?-18:18),(cy+y)/2-5,'#087b60',c.x>=0?'right':'left');}}
arrow(cx,cy,x,y,'#b73860',4);ctx.beginPath();ctx.arc(x,y,9,0,2*Math.PI);ctx.fillStyle='#b73860';ctx.fill();ctx.strokeStyle='white';ctx.lineWidth=3;ctx.stroke();if(state.values&&state.force>0)label('F = '+fmt(state.force)+' N',x+(c.x<0?-15:15),y-16,'#b73860',c.x<0?'right':'left');ctx.beginPath();ctx.arc(cx,cy,4,0,Math.PI*2);ctx.fillStyle='#16344b';ctx.fill();label(state.force===0?'F = 0 N':'θ = '+state.angle.toFixed(1)+'°',105,58,'#7651a5');
}
function update(sync=true){const c=P.components(state.force,state.angle);if(sync){$('magnitude').value=state.force;$('magnitudeNumber').value=state.force.toFixed(1);$('angle').value=state.angle;$('angleNumber').value=state.angle.toFixed(1);} $('fx').textContent=fmt(c.x)+' N';$('fy').textContent=fmt(c.y)+' N';$('quadrant').textContent=P.position(state.force,state.angle);$('analysis').textContent=state.force===0?'แรงเป็นศูนย์: องค์ประกอบทั้งสองเป็นศูนย์ และเวกเตอร์ไม่มีทิศทางแน่นอน':`Fₓ ${c.x===0?'เป็นศูนย์':c.x>0?'ชี้ไปทางขวา (+x)':'ชี้ไปทางซ้าย (−x)'} • Fᵧ ${c.y===0?'เป็นศูนย์':c.y>0?'ชี้ขึ้น (+y)':'ชี้ลง (−y)'}`;$('substitution').textContent=`แทนค่า: Fₓ = ${fmt(state.force)} cos(${state.angle.toFixed(1)}°) = ${fmt(c.x)} N และ Fᵧ = ${fmt(state.force)} sin(${state.angle.toFixed(1)}°) = ${fmt(c.y)} N (ปัดเศษ 2 ตำแหน่ง)`;draw();}
let raf=0,last=0;
function stop(){state.running=false;cancelAnimationFrame(raf);$('animate').textContent='▶ หมุนเวกเตอร์อัตโนมัติ';$('animate').setAttribute('aria-pressed','false');last=0;}
function tick(time){if(!state.running)return;if(last)state.angle=(state.angle+Math.min((time-last)/1000,.1)*20)%360;last=time;update();raf=requestAnimationFrame(tick);}
$('animate').onclick=()=>{if(state.running){stop();return;}state.running=true;$('animate').textContent='❚❚ หยุดการหมุน';$('animate').setAttribute('aria-pressed','true');raf=requestAnimationFrame(tick);};
document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();});
for(const [slider,number,prop,max] of [['magnitude','magnitudeNumber','force',20],['angle','angleNumber','angle',360]]){
 $(slider).oninput=()=>{stop();state[prop]=Number($(slider).value);update();};
 $(number).oninput=()=>{if($(number).value===''||!Number.isFinite($(number).valueAsNumber))return;stop();state[prop]=Math.max(0,Math.min(max,$(number).valueAsNumber));$(slider).value=state[prop];update(false);};
 $(number).onchange=()=>update();$(number).onblur=()=>update();
}
$('showComponents').onchange=e=>{state.components=e.target.checked;draw();};$('showValues').onchange=e=>{state.values=e.target.checked;draw();};
function set(force,angle){stop();state.force=force;state.angle=angle;update();}
document.querySelectorAll('[data-angle]').forEach(b=>b.onclick=()=>set(state.force,Number(b.dataset.angle)));
$('reset').onclick=()=>{state.components=true;state.values=true;$('showComponents').checked=true;$('showValues').checked=true;set(10,30);};
function coords(e){const rect=canvas.getBoundingClientRect();return {x:(e.clientX-rect.left)*800/rect.width,y:(e.clientY-rect.top)*680/rect.height};}
let drag=null;
canvas.onpointerdown=e=>{const pt=coords(e),v=P.components(state.force,state.angle);if(Math.hypot(pt.x-cx-v.x*scale,pt.y-cy+v.y*scale)>35)return;stop();drag=e.pointerId;canvas.setPointerCapture(e.pointerId);};
canvas.onpointermove=e=>{if(drag!==e.pointerId)return;const pt=coords(e),v=P.fromPoint((pt.x-cx)/scale,(cy-pt.y)/scale);state.force=Math.round(v.force*10)/10;if(v.angle!==null)state.angle=Math.round(v.angle*10)/10;update();};
canvas.onpointerup=canvas.onpointercancel=()=>{drag=null;};canvas.onlostpointercapture=()=>{drag=null;};
const missions=[{angle:30,text:'ตั้ง F = 10 N และ θ = 30° แล้วเปรียบเทียบขนาด Fₓ กับ Fᵧ'},{angle:150,text:'ตั้ง F = 10 N และ θ = 150° องค์ประกอบใดเป็นลบ? เปรียบเทียบกับมุม 30°'},{angle:90,text:'ตั้ง F = 10 N และ θ = 90° แล้วทดลอง 180° และ 270° องค์ประกอบใดเป็นศูนย์ในแต่ละมุม?'}];
document.querySelectorAll('[data-mission]').forEach(b=>b.onclick=()=>{const m=missions[Number(b.dataset.mission)];set(10,m.angle);$('mission').textContent=m.text;});
const questions=[{q:'แรงขนาด 10 N ทำมุม 30° กับแกน +x มี Fₓ และ Fᵧ เท่าใด?',options:['Fₓ ≈ 8.66 N, Fᵧ = 5.00 N','Fₓ = 5.00 N, Fᵧ ≈ 8.66 N','Fₓ = 10 N, Fᵧ = 10 N'],answer:0,why:'Fₓ = F cos θ = 10 cos 30° ≈ 8.66 N และ Fᵧ = F sin θ = 10 sin 30° = 5.00 N'},{q:'เมื่อแรงอยู่ในควอดแรนต์ที่ 2 องค์ประกอบมีเครื่องหมายอย่างไร?',options:['Fₓ > 0, Fᵧ < 0','Fₓ < 0, Fᵧ > 0','Fₓ < 0, Fᵧ < 0'],answer:1,why:'ควอดแรนต์ที่ 2 อยู่ทางซ้ายและด้านบนของจุดกำเนิด จึงมีองค์ประกอบ x เป็นลบ และ y เป็นบวก'},{q:'ถ้า Fₓ = −6 N และ Fᵧ = −8 N ขนาดแรงเท่ากับเท่าใด?',options:['−14 N','2 N','10 N'],answer:2,why:'ขนาดแรง F = √[(-6)² + (-8)²] = √100 = 10 N ขนาดเป็นบวก ส่วนเครื่องหมายขององค์ประกอบบอกทิศ'}];let answers={};
function buildQuiz(){answers={};$('quiz').innerHTML=questions.map((q,i)=>`<div class="question" id="q${i}"><h3>ข้อ ${i+1} · ${q.q}</h3>${q.options.map((opt,j)=>`<label><input type="radio" name="q${i}" value="${j}"> ${opt}</label>`).join('')}<button data-check="${i}">ตรวจคำตอบข้อ ${i+1}</button><p class="feedback" id="feedback${i}" aria-live="polite"></p></div>`).join('');$('score').textContent='คะแนน 0 / 3 • ตอบแล้ว 0 ข้อ';document.querySelectorAll('[data-check]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.check),chosen=document.querySelector(`input[name="q${i}"]:checked`),feedback=$('feedback'+i);if(!chosen){feedback.textContent='กรุณาเลือกคำตอบก่อนตรวจ';return;}const correct=Number(chosen.value)===questions[i].answer;answers[i]=correct;feedback.className='feedback '+(correct?'correct':'incorrect');feedback.textContent=(correct?'ถูกต้อง · ':'ยังไม่ถูกต้อง · ')+questions[i].why;document.querySelectorAll(`input[name="q${i}"]`).forEach(e=>e.disabled=true);b.disabled=true;$('score').textContent=`คะแนน ${Object.values(answers).filter(Boolean).length} / 3 • ตอบแล้ว ${Object.keys(answers).length} ข้อ`;});}
$('retry').onclick=buildQuiz;buildQuiz();update();document.fonts.ready.then(draw);
