'use strict';const $=id=>document.getElementById(id),P=ElevatorPhysics,c=$('scene').getContext('2d');let state={m:60,a:0,v0:0,t:0},running=false,last=null,frame=0;const fmt=x=>(Math.abs(x)<.00001?0:x).toFixed(2);
function text(t,x,y,color='#173b53',size=20){c.fillStyle=color;c.font=size+'px Sarabun,sans-serif';c.textAlign='center';c.fillText(t,x,y);}
function arrow(x,y,Y,color){if(Math.abs(Y-y)<.01)return;const dir=Math.sign(Y-y);c.strokeStyle=color;c.lineWidth=4;c.beginPath();c.moveTo(x,y);c.lineTo(x,Y);c.stroke();c.fillStyle=color;c.beginPath();c.moveTo(x,Y);c.lineTo(x-8,Y-dir*14);c.lineTo(x+8,Y-dir*14);c.fill();}
function draw(q){c.clearRect(0,0,800,600);c.fillStyle='#edf4fa';c.fillRect(35,30,365,535);for(let s=-30;s<=30;s+=5){const y=425-s*4;c.strokeStyle='#d5e1ec';c.lineWidth=1;c.beginPath();c.moveTo(40,y);c.lineTo(395,y);c.stroke();text(s+' m',62,y-5,'#617c8d',14);}const top=180-q.s*4;c.fillStyle='#fff';c.fillRect(115,top,255,245);c.strokeStyle='#748ca1';c.lineWidth=3;c.strokeRect(115,top,255,245);c.fillStyle='#edf5fa';c.fillRect(180,top+190,125,40);c.strokeRect(180,top+190,125,40);text(fmt(q.reading)+' kg',242,top+217,'#165c77',18);c.fillStyle='#193d55';c.beginPath();c.arc(242,top+79,16,0,2*Math.PI);c.fill();c.strokeStyle='#193d55';c.lineWidth=12;c.lineCap='round';c.beginPath();c.moveTo(242,top+100);c.lineTo(242,top+143);c.moveTo(218,top+110);c.lineTo(218,top+148);c.moveTo(266,top+110);c.lineTo(266,top+148);c.moveTo(242,top+143);c.lineTo(227,top+183);c.moveTo(242,top+143);c.lineTo(257,top+183);c.stroke();c.lineCap='butt';text('ลิฟต์: s = '+fmt(q.s)+' m',240,top+28);text('v = '+fmt(q.v)+' m/s',240,top+265);text('FBD ของคน',590,58);const scale=.12;arrow(590,295,295-q.normal*scale,'#15865b');arrow(590,295,295+q.weight*scale,'#c44359');c.beginPath();c.arc(590,295,7,0,2*Math.PI);c.fillStyle='#193d55';c.fill();text('N = '+fmt(q.normal)+' N',590,Math.max(88,275-q.normal*scale),'#15865b');text('mg = '+fmt(q.weight)+' N',590,330+q.weight*scale,'#c44359');text('แกนบวก ↑',713,55);text('a = '+fmt(state.a)+' m/s²',590,505);text('แรงลัพธ์ = '+fmt(q.normal-q.weight)+' N',590,540);}
function update(sync=true){const q=P.calculate(state.m,state.a,state.v0,state.t);if(sync)for(const [id,key]of [['mass','m'],['accel','a'],['velocity','v0']]){$(id).value=state[key];$(id+'Number').value=state[key];}$('time').value=state.t;$('timeOut').textContent=fmt(state.t);$('weight').textContent=fmt(q.weight)+' N';$('normal').textContent=fmt(q.normal)+' N';$('reading').textContent=fmt(q.reading)+' kg';let motion=Math.abs(q.v)<1e-8?(state.a===0?'หยุดนิ่ง':'ความเร็วเป็นศูนย์ขณะนี้ แต่ยังมีความเร่ง'):(q.v>0?'กำลังขึ้น':'กำลังลง')+(state.a===0?'ด้วยความเร็วคงตัว':q.v*state.a>0?'และเร็วขึ้น':'และช้าลง');$('motion').textContent=motion+' · v = '+fmt(q.v)+' m/s · a = '+fmt(state.a)+' m/s²';$('comparison').textContent=q.normal===0?'ไร้น้ำหนักปรากฏ: N = 0 แต่แรงโน้มถ่วงยังมีอยู่':state.a>0?'ตาชั่งอ่านมากกว่าค่าน้ำหนักปกติ: N > mg':state.a<0?'ตาชั่งอ่านน้อยกว่าค่าน้ำหนักปกติ: N < mg':'ตาชั่งอ่านน้ำหนักปกติ: N = mg';$('calculation').textContent=`กำหนดขึ้นเป็นบวก: N − mg = ma → N = ${state.m}(9.8 + (${fmt(state.a)})) = ${fmt(q.normal)} N ค่าหน้าปัด = N/9.8 = ${fmt(q.reading)} kg; มวลจริง m = ${state.m} kg`;draw(q);}
function stop(){running=false;cancelAnimationFrame(frame);last=null;$('play').textContent=state.t>=2?'▶ ทดลองซ้ำ':'▶ เล่นต่อ / เริ่ม';}
function tick(now){if(!running)return;if(last!==null)state.t=Math.min(2,state.t+Math.min((now-last)/1000,.05));last=now;update();if(state.t>=2){stop();return;}frame=requestAnimationFrame(tick);}
$('play').onclick=()=>{if(running){stop();return;}if(state.t>=2)state.t=0;running=true;last=null;$('play').textContent='❚❚ พักภาพ';frame=requestAnimationFrame(tick);};$('restart').onclick=()=>{stop();state.t=0;update();};$('time').oninput=()=>{stop();state.t=Number($('time').value);update();};document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();});
for(const [id,key,min,max,step]of [['mass','m',20,100,1],['accel','a',-9.8,9.8,.1],['velocity','v0',-5,5,.1]]){function change(value,sync){if(!Number.isFinite(value))return;stop();state.t=0;state[key]=Number((Math.round(Math.max(min,Math.min(max,value))/step)*step).toFixed(1));$('scenario').value='custom';$(id).value=state[key];update(sync);}$(id).oninput=()=>change(Number($(id).value),true);$(id+'Number').oninput=()=>change($(id+'Number').valueAsNumber,false);$(id+'Number').onchange=$(id+'Number').onblur=()=>update();}
const presets={rest:[0,0],constant:[2,0],upfast:[2,2],upslow:[5,-2],downfast:[-2,-2],downslow:[-5,2],fall:[0,-9.8]};$('scenario').onchange=()=>{const p=presets[$('scenario').value];if(!p)return;stop();state.v0=p[0];state.a=p[1];state.t=0;update();};$('reset').onclick=()=>{stop();state={m:60,a:0,v0:0,t:0};$('scenario').value='rest';update();};update();document.fonts.ready.then(()=>update());
