'use strict';
const $=id=>document.getElementById(id),P=GravityPhysics,scene=$('scene'),ctx=scene.getContext('2d'),plot=$('plot'),pc=plot.getContext('2d');let state={m1:20,m2:40,r:4},baseline={...state};
const sci=x=>{const [a,b]=x.toExponential(3).split('e');const supers={'-':'⁻','0':'⁰','1':'¹','2':'²','3':'³','4':'⁴','5':'⁵','6':'⁶','7':'⁷','8':'⁸','9':'⁹'};return a+' × 10'+String(Number(b)).split('').map(c=>supers[c]).join('');};
function text(c,t,x,y,color='#16344b',align='center',size=20){c.font=size+'px Sarabun, sans-serif';c.fillStyle=color;c.textAlign=align;c.fillText(t,x,y);}
function line(c,x,y,X,Y,color='#96adbd',width=2){c.strokeStyle=color;c.lineWidth=width;c.beginPath();c.moveTo(x,y);c.lineTo(X,Y);c.stroke();}
function arrow(x,X,y,color){line(ctx,x,y,X,y,color,5);const d=Math.sign(X-x);ctx.fillStyle=color;ctx.beginPath();ctx.moveTo(X,y);ctx.lineTo(X-d*13,y-8);ctx.lineTo(X-d*13,y+8);ctx.closePath();ctx.fill();}
function drawScene(){ctx.clearRect(0,0,800,430);const x1=85,x2=85+state.r*61,y=205;line(ctx,50,y,750,y,'#d5e3ec');for(const [x,color,label] of [[x1,'#146eae','m₁'],[x2,'#bf6b18','m₂']]){ctx.fillStyle=color;ctx.beginPath();ctx.arc(x,y,23,0,Math.PI*2);ctx.fill();text(ctx,label,x,y+7,'white');}arrow(x1,x1+90,110,'#146eae');arrow(x2,x2-90,285,'#bf6b18');line(ctx,x1,135,x1,y-27,'#8eb5d0');line(ctx,x2,y+27,x2,265,'#d7b388');text(ctx,'แรงบน m₁ →',x1+52,77,'#146eae');text(ctx,'← แรงบน m₂',Math.max(110,x2-46),320,'#bf6b18');line(ctx,x1,359,x2,359);line(ctx,x1,346,x1,372);line(ctx,x2,346,x2,372);text(ctx,'r = '+state.r.toFixed(1)+' m',(x1+x2)/2,402);text(ctx,state.m1+' kg',x1,250,'#146eae');text(ctx,state.m2+' kg',x2,170,'#bf6b18');}
function drawPlot(){pc.clearRect(0,0,800,360);const left=90,right=755,top=35,bottom=290,max=P.calculate(state.m1,state.m2,1).force*1e9;const X=r=>left+(r-1)/9*(right-left),Y=f=>bottom-f/max*(bottom-top);for(let i=0;i<=4;i++){const y=bottom-i/4*(bottom-top);line(pc,left,y,right,y,'#e2ebf2',1);text(pc,(max*i/4).toFixed(max<10?2:0),left-10,y+6,'#526d7c','right',16);}for(let r=1;r<=10;r++){const x=X(r);line(pc,x,bottom,x,bottom+5);text(pc,r,x,bottom+25,'#526d7c','center',16);}line(pc,left,top,left,bottom);line(pc,left,bottom,right,bottom);text(pc,'F (nN)',left,21);text(pc,'r (m)',right,340);pc.beginPath();for(let r=1;r<=10.001;r+=.025){const x=X(r),y=Y(P.calculate(state.m1,state.m2,r).force*1e9);if(r===1)pc.moveTo(x,y);else pc.lineTo(x,y);}pc.strokeStyle='#126e91';pc.lineWidth=3;pc.stroke();const f=P.calculate(state.m1,state.m2,state.r).force*1e9;pc.fillStyle='#c76b20';pc.beginPath();pc.arc(X(state.r),Y(f),6,0,2*Math.PI);pc.fill();}
function update(sync=true){const v=P.calculate(state.m1,state.m2,state.r),b=P.calculate(baseline.m1,baseline.m2,baseline.r);if(sync)for(const [id,key] of [['mass1','m1'],['mass2','m2'],['distance','r']]){$(id).value=state[key];$(id+'Number').value=state[key];}$('f1').textContent=sci(v.force)+' N';$('f2').textContent=sci(v.force)+' N';$('rValue').textContent=state.r.toFixed(1)+' m';$('acceleration').textContent=`ถ้ามีเพียงแรงดึงดูด: a₁ = ${sci(v.a1)} m/s² ไปทางขวา และ a₂ = ${sci(v.a2)} m/s² ไปทางซ้าย`;$('baseline').textContent=`ค่าอ้างอิง: m₁ = ${baseline.m1} kg, m₂ = ${baseline.m2} kg, r = ${baseline.r.toFixed(1)} m`;$('ratio').textContent=`แรงใหม่ / แรงอ้างอิง = ${(v.force/b.force).toFixed(3)} เท่า`;$('substitution').textContent=`F = (6.67430 × 10⁻¹¹ × ${state.m1} × ${state.m2}) / (${state.r.toFixed(1)})² = ${sci(v.force)} N ≈ ${(v.force*1e9).toFixed(3)} nN`;$('plotText').textContent=`จุดสีส้ม: ระยะ ${state.r.toFixed(1)} m, แรง ${(v.force*1e9).toFixed(3)} nN เมื่อ m₁ = ${state.m1} kg และ m₂ = ${state.m2} kg`;drawScene();drawPlot();}
for(const [id,key,min,max,step] of [['mass1','m1',1,100,1],['mass2','m2',1,100,1],['distance','r',1,10,.1]]){$(id).oninput=()=>{state[key]=Number($(id).value);update();};$(id+'Number').oninput=()=>{const n=$(id+'Number').valueAsNumber;if(!Number.isFinite(n))return;state[key]=Math.round(Math.max(min,Math.min(max,n))/step)*step;state[key]=Number(state[key].toFixed(1));$(id).value=state[key];update(false);};$(id+'Number').onchange=$(id+'Number').onblur=()=>update();}
$('reference').onclick=()=>{baseline={...state};update();};$('reset').onclick=()=>{state={m1:20,m2:40,r:4};baseline={...state};$('mission').textContent='กดบันทึกค่าอ้างอิง แล้วเปลี่ยนตัวแปรทีละตัวเพื่ออ่านอัตราส่วนแรงใหม่ต่อแรงอ้างอิง';update();};
document.querySelectorAll('[data-mission]').forEach(b=>b.onclick=()=>{baseline={m1:20,m2:40,r:4};state={...baseline};const k=b.dataset.mission;if(k==='mass'){state.m1=40;$('mission').textContent='มวลหนึ่งเพิ่มจาก 20 เป็น 40 kg โดยมวลสองและระยะคงเดิม เปรียบเทียบแรงกับค่าอ้างอิง';}else if(k==='distance'){state.r=8;$('mission').textContent='ระยะเพิ่มจาก 4 เป็น 8 m โดยมวลทั้งสองคงเดิม เปรียบเทียบแรงกับค่าอ้างอิง';}else{state.m1=40;state.m2=80;$('mission').textContent='มวลทั้งสองเพิ่มเป็นสองเท่า โดยระยะคงเดิม เปรียบเทียบแรงกับค่าอ้างอิง';}update();});
let dragging=null;function pos(e){const b=scene.getBoundingClientRect();return{x:(e.clientX-b.left)*800/b.width,y:(e.clientY-b.top)*430/b.height};}scene.onpointerdown=e=>{const p=pos(e);if(Math.hypot(p.x-(85+state.r*61),p.y-205)>36)return;dragging=e.pointerId;scene.setPointerCapture(e.pointerId);};scene.onpointermove=e=>{if(dragging!==e.pointerId)return;state.r=Math.round(Math.max(1,Math.min(10,(pos(e).x-85)/61))*10)/10;update();};scene.onpointerup=scene.onpointercancel=scene.onlostpointercapture=()=>dragging=null;update();document.fonts.ready.then(()=>{drawScene();drawPlot();});
