(()=>{'use strict';const $=id=>document.getElementById(id);let mode='explore',visited=false,rows=[],cleared=[];
function sample(){const angle=Number($('angle').value),m=Number($('mass').value),mu=Number($('mu').value),rad=angle*Math.PI/180,N=m*9.8*Math.cos(rad),need=m*9.8*Math.sin(rad),max=mu*N,critical=Math.atan(mu)*180/Math.PI,delta=angle-critical;const state=delta>1e-6?'slip':delta>=-1e-6?'limit':need/max>=.95?'near':'stick';return{angle,m,mu,N,need,max,critical,state,mode};}
const names={stick:'สมดุลสถิต',near:'ใกล้ขีดจำกัด (ยังสมดุล)',limit:'สมดุลจำกัด',slip:'เริ่มไถล · พ้นช่วงสถิต'},modes={explore:'ตั้งค่า',a:'Mission A',b:'Mission B'};
function render(){const s=sample();$('status').className='status '+s.state;$('status').textContent=names[s.state];if(s.state==='near')$('stateExplain').textContent='แรงเสียดทานสถิตเข้าใกล้ค่าสูงสุด แต่ยังรักษาสมดุลได้ เกณฑ์สีเตือนเริ่มที่อัตราส่วน 0.95';$('gauge').classList.toggle('near',s.state==='near');$('gauge').classList.toggle('at-limit',s.state==='limit');const L=80,R=850,T=35,B=300,cap=s.m*9.8,X=a=>L+a/60*(R-L),Y=f=>B-f/cap*(B-T);let h='';const line=(x,y,xx,yy,color,dash='')=>`<path d="M${x} ${y}L${xx} ${yy}" fill="none" stroke="${color}" stroke-width="2" ${dash?`stroke-dasharray="${dash}"`:''}/>`;const label=(x,y,t,anchor='middle')=>`<text x="${x}" y="${y}" text-anchor="${anchor}" fill="#17304d" font-size="16">${t}</text>`;
for(let i=0;i<=4;i++){const f=cap*i/4;h+=line(L,Y(f),R,Y(f),'#e0e9f1')+label(L-10,Y(f)+5,f.toFixed(2),'end');}for(let a=0;a<=60;a+=10)h+=label(X(a),B+26,a);h+=line(L,T,L,B,'#8299ac')+line(L,B,R,B,'#8299ac')+label(42,20,'แรง (N)')+label(R,360,'θ (°)');
for(const [fn,color] of [[a=>cap*Math.sin(a*Math.PI/180),'#216eb5'],[a=>s.mu*cap*Math.cos(a*Math.PI/180),'#8b45ad']]){let d='';for(let a=0;a<=60;a+=.25)d+=(a===0?'M':'L')+X(a)+' '+Y(fn(a));h+=`<path d="${d}" fill="none" stroke="${color}" stroke-width="3"/>`;}
h+=line(X(s.angle),T,X(s.angle),B,'#607d8b','5 5');for(const [f,c] of [[s.need,'#216eb5'],[s.max,'#8b45ad']])h+=`<circle cx="${X(s.angle)}" cy="${Y(f)}" r="6" fill="${c}" stroke="white" stroke-width="2"/>`;
if($('critical').checked&&(mode!=='a'||visited)){const x=X(s.critical),y=Y(s.m*9.8*Math.sin(s.critical*Math.PI/180));h+=`<circle cx="${x}" cy="${y}" r="10" fill="none" stroke="#bd5b17" stroke-width="3"/>`+label(x,Math.max(22,y-20),'θ꜀ = '+s.critical.toFixed(3)+'°');}
$('forceChart').innerHTML=h;$('chartSummary').textContent=`มุมปัจจุบัน ${s.angle.toFixed(3)}°: mg sin θ = ${s.need.toFixed(3)} N; μₛN = ${s.max.toFixed(3)} N · ${names[s.state]}`;
}
function table(){ $('recordBody').innerHTML=rows.length?rows.map((s,i)=>`<tr><td>${i+1}</td><td>${modes[s.mode]}</td><td>${s.angle.toFixed(6)}</td><td>${s.m.toFixed(1)}</td><td>${s.mu.toFixed(2)}</td><td>${s.N.toFixed(3)}</td><td>${s.need.toFixed(3)}</td><td>${s.state==='slip'?'พ้นช่วงสถิต':Math.min(s.need,s.max).toFixed(3)}</td><td>${s.max.toFixed(3)}</td><td>${names[s.state]}</td></tr>`).join(''):'<tr><td colspan="10" style="text-align:center">ยังไม่มีผลการทดลอง</td></tr>';$('removeSample').disabled=$('clearSamples').disabled=rows.length===0;$('undoSamples').disabled=cleared.length===0;}
$('recordSample').onclick=()=>{if(rows.length>=500){$('recordMessage').textContent='บันทึกครบ 500 แถวแล้ว กรุณาจัดเก็บผลก่อนล้างตาราง';return;}rows.push(sample());table();$('recordMessage').textContent='บันทึกผลครั้งที่ '+rows.length+' แล้ว';};$('removeSample').onclick=()=>{rows.pop();table();$('recordMessage').textContent='ลบแถวล่าสุดแล้ว';};$('clearSamples').onclick=()=>{cleared=rows;rows=[];table();$('recordMessage').textContent='ล้างตารางแล้ว กดคืนค่าตารางก่อนล้างเพื่อเรียกกลับ';};$('undoSamples').onclick=()=>{rows=cleared.concat(rows);cleared=[];table();$('recordMessage').textContent='คืนค่าตารางแล้ว';};window.addEventListener('inclinechange',e=>{mode=e.detail.mode;visited=e.detail.visitedCritical;render();});render();table();})();
